[[repos]]
repo = "local"

[[repos.hooks]]
id = "biome"
name = "biome"
language = "system"
entry = "bun x @biomejs/biome check --write --no-errors-on-unmatched"
files = {
  glob = "**/*.{js,ts,jsx,tsx,json,jsonc}"
}

[[repos.hooks]]
id = "ast-grep"
name = "ast-grep"
language = "system"
entry = "ast-grep scan"

[[repos.hooks]]
id = "type-check"
name = "type-check"
language = "system"
entry = "tsc --noEmit -p tsconfig.json"
pass_filenames = false
