[[repos]]
repo = "local"
hooks = [
  { id = "biome", name = "biome", language = "system", entry = "bun x @biomejs/biome check --write --no-errors-on-unmatched", files = { glob = "**/*.{js,ts,jsx,tsx,json,jsonc}" } },
  { id = "ast-grep", name = "ast-grep", language = "system", entry = "ast-grep scan" },
  { id = "type-check", name = "type-check", language = "system", entry = "bun x tsc --noEmit", pass_filenames = false }
]
